CREATE TABLE BLOCK (
   ID                  BIGINT PRIMARY KEY,
   TEXT                TEXT NOT NULL,
   RATE                INT NOT NULL,
   CREATE_DATETIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE SEQ_BLOCK INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE;